name: Tests

on:
  workflow_dispatch:
  push:
  pull_request:

defaults:
  run:
    shell: bash -l {0}

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11', '3.12']
        env: [base]
    env:
      SYMMRAY_DEBUG: "1"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          python-version: ${{ matrix.python-version }}

      - name: Setup uv project
        run: uv sync

      - name: Install dependencies
        run: uv pip install -r ci/requirements/${{ matrix.env }}.txt

      - name: Test with pytest
        run: uv run pytest --cov=symmray tests/ --cov-report=xml tests

      - name: Report to codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
